# -*- coding: utf-8 -*-
"""Resolve a gateway credential into the binding it authorizes.

Why this is not part of ``app/access.py``: ``verify_workspace_access`` answers a
yes/no question and treats the workspace token as owner-equivalent. A gateway
credential must answer a much narrower question — *which* agent, *which*
external conversations — and a boolean cannot carry that. Folding it into the
shared check would hand the gateway the whole workspace: every event, every
file, every browser tab, and the ability to post as any source it liked.

So integration calls get their own credential, their own dependency, and their
own endpoints. They never carry a workspace token.

The secret itself is generated by the gateway, which keeps the plaintext and
sends us only the SHA-256. Nothing here can recover it, which is the point:
there is no plaintext to leak, and re-sending an activation with the same
fingerprint is naturally idempotent rather than minting a second credential.
"""

import hashlib
import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional

from fastapi import Depends, Header, HTTPException
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.database import get_db
from app.models import IntegrationBinding, IntegrationKey

logger = logging.getLogger(__name__)

# Statuses a binding may serve traffic in. `disconnecting` is excluded: once a
# disconnect is requested we stop accepting inbound work, and only the outbound
# flush and the gateway's cleanup ACK remain.
SERVING_STATUSES = frozenset({"active"})


def hash_key(plaintext: str) -> str:
    """Fingerprint a gateway credential. The only form we ever store."""
    return hashlib.sha256(plaintext.encode("utf-8")).hexdigest()


@dataclass(frozen=True)
class IntegrationPrincipal:
    """Who the caller is, expressed as the binding it may act for.

    Endpoints read `workspace_id` and `agent_name` from here and write them
    into the events they build — they are never taken from the request, so a
    compromised or buggy gateway cannot post as another agent or into another
    workspace.
    """

    binding_id: str
    workspace_id: str
    agent_name: str
    platform: str
    allowed_scope: dict = field(default_factory=dict)

    @property
    def channel_prefix(self) -> str:
        """Prefix every channel of this binding shares.

        Also the filter the outbound event stream subscribes on, which is why
        the binding id is baked into the channel name (see `conversations`).
        """
        return f"integration:{self.binding_id}:"

    def allows_dm(self) -> bool:
        # Absent scope means DM-only — the narrowest useful default, and what a
        # binding created before channel selection existed should behave as.
        if not self.allowed_scope:
            return True
        return bool(self.allowed_scope.get("dm", True))

    def allows_channel(self, external_channel_id: str) -> bool:
        """True when this binding was granted the named external channel.

        An empty or missing `channels` list means no group conversations were
        selected, not "all of them" — scope widens only by explicit choice.
        """
        allowed = (self.allowed_scope or {}).get("channels") or []
        return external_channel_id in set(allowed)


def _resolve(db: Session, presented: str) -> Optional[IntegrationPrincipal]:
    key_row = db.execute(
        select(IntegrationKey).where(
            IntegrationKey.key_hash == hash_key(presented),
            IntegrationKey.revoked_at.is_(None),
        )
    ).scalar_one_or_none()
    if key_row is None:
        return None

    binding = db.execute(
        select(IntegrationBinding).where(IntegrationBinding.id == key_row.binding_id)
    ).scalar_one_or_none()
    if binding is None or binding.status not in SERVING_STATUSES:
        return None

    return IntegrationPrincipal(
        binding_id=binding.id,
        workspace_id=str(binding.workspace_id),
        agent_name=binding.agent_name,
        platform=binding.platform,
        allowed_scope=binding.external_scope or {},
    )


def require_gateway_key(
    x_integration_key: Optional[str] = Header(None),
    db: Session = Depends(get_db),
) -> IntegrationPrincipal:
    """FastAPI dependency for every gateway-facing endpoint.

    Raises 401 rather than returning an error body because there is no useful
    partial result: a request whose credential doesn't resolve has no binding,
    so it has no workspace and no agent to act for.
    """
    if not x_integration_key:
        raise HTTPException(status_code=401, detail="Missing integration credential")

    principal = _resolve(db, x_integration_key)
    if principal is None:
        # Deliberately indistinguishable from a revoked or disconnected
        # binding — a caller probing with guessed credentials learns nothing
        # about which of them exist.
        raise HTTPException(status_code=401, detail="Invalid integration credential")

    return principal


def revoke_keys(db: Session, binding_id: str) -> int:
    """Revoke every live credential for a binding. Does not commit."""
    now = datetime.now(timezone.utc)
    rows = db.execute(
        select(IntegrationKey).where(
            IntegrationKey.binding_id == binding_id,
            IntegrationKey.revoked_at.is_(None),
        )
    ).scalars().all()
    for row in rows:
        row.revoked_at = now
    return len(rows)
