network_name: "shared_document_demo"
network_type: "centralized"

discovery:
  mod_name: "agent_discovery"
  auto_discovery: true
  heartbeat_interval: 30
  
communication:
  mod_name: "shared_document"
  
transport:
  type: "tcp"
  tcp:
    host: "localhost"
    port: 8888
    
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
