# OpenConvert Demo Network Configuration
# This configuration sets up a centralized network for OpenConvert file conversion services

# Core network configuration
network:
  name: "OpenConvertDemoNetwork"
  mode: "centralized"  # Centralized network topology
  node_id: "openconvert-coordinator"  # Unique identifier for this coordinator
  
  # Server/Coordinator settings
  host: "0.0.0.0"  # Bind to all interfaces
  port: 8765  # Port for incoming connections
  server_mode: true  # This node acts as the coordinator/server
  
  # Transport configuration
  transport: "websocket"  # WebSocket transport
  transport_config:
    buffer_size: 8192
    compression: true
    ping_interval: 30
    ping_timeout: 10
    max_message_size: 10485760  # 10MB for file transfers
  
  # Security configuration
  encryption_enabled: false  # Disabled for demo simplicity
  
  # Discovery configuration
  discovery_interval: 5
  discovery_enabled: true
  
  # Connection management
  max_connections: 50
  connection_timeout: 30.0
  retry_attempts: 3
  heartbeat_interval: 30
  
  # Messaging configuration
  message_queue_size: 1000
  message_timeout: 60.0  # Longer timeout for file conversions
  message_routing_enabled: true
  
  # Protocol configuration
  protocols:
    - name: "openagents.protocols.communication.simple_messaging"
      enabled: true
      config:
        max_message_size: 10485760  # 10MB
        message_retention_time: 300
        enable_message_history: true
    - name: "openagents.protocols.discovery.agent_discovery"
      enabled: true
      config:
        announce_interval: 30
        cleanup_interval: 60
        agent_timeout: 120
    - name: "openagents.protocols.discovery.openconvert_discovery"
      enabled: true
      config:
        announce_interval: 30
        cleanup_interval: 60

# Service agents configuration (commented out - run manually)
# service_agents:
#   - name: "OpenConvert-ImageAgent"
#     protocol_names:
#       - "openagents.protocols.communication.simple_messaging"
#       - "openagents.protocols.discovery.openconvert_discovery"
#     agent_script: "demos/openconvert/run_agent.py"
#     agent_args: ["image"]

# Network profile for discovery
network_profile:
  discoverable: true
  name: "OpenConvert Demo Network"
  description: "A demo network for OpenConvert file conversion services"
  tags:
    - "openconvert"
    - "demo"
    - "file-conversion"
  categories:
    - "demo"
    - "file-services"
  country: "Worldwide"
  required_openagents_version: "0.5.0"
  capacity: 50
  authentication:
    type: "none"
  host: "0.0.0.0"
  port: 8765

# Global settings
log_level: "INFO"
data_dir: "./data/openconvert-demo"

# Runtime configuration
runtime_limit: null
shutdown_timeout: 30