# Example network configuration for OpenAgents

network:
  name: "example-network"
  protocols:
    discovery:
      type: "openagents.protocols.discovery.network_protocol.DiscoveryNetworkProtocol"
      enabled: true
      config:
        cleanup_interval: 60.0
        max_inactive_time: 300.0
    
    communication:
      type: "openagents.protocols.communication.network_protocol.CommunicationNetworkProtocol"
      enabled: true
      config:
        max_message_size: 1048576  # 1MB
        max_history_size: 1000

agents:
  - name: "service-provider"
    protocols:
      discovery:
        type: "openagents.protocols.discovery.agent_protocol.DiscoveryAgentProtocol"
        enabled: true
        config:
          service_refresh_interval: 60.0
      
      communication:
        type: "openagents.protocols.communication.agent_protocol.CommunicationAgentProtocol"
        enabled: true
        config:
          message_timeout: 30.0
    
    services:
      - name: "data-processing"
        description: "Process data using advanced algorithms"
        input_format: "JSON"
        output_format: "JSON"
    
    subscriptions:
      - "requests"
  
  - name: "service-consumer"
    protocols:
      discovery:
        type: "openagents.protocols.discovery.agent_protocol.DiscoveryAgentProtocol"
        enabled: true
      
      communication:
        type: "openagents.protocols.communication.agent_protocol.CommunicationAgentProtocol"
        enabled: true
    
    subscriptions:
      - "responses" 