# AWS Bedrock Claude Agent Configuration Example
# This demonstrates configuration for Claude models via AWS Bedrock

type: "simple"

config:
  agent_id: "bedrock-claude-001"
  model_name: "anthropic.claude-3-sonnet-20240229-v1:0"
  
  # Specify Bedrock provider
  provider: "bedrock"
  
  # Optional: AWS region (defaults to us-east-1)
  region: "us-east-1"
  
  instruction: |
    You are Claude running on AWS Bedrock, operating in an OpenAgents network.
    You can communicate with other agents and help users with various tasks.
    Leverage enterprise-grade AWS infrastructure for reliable responses.
    
  protocol_names:
    - "openagents.mods.communication.simple_messaging"

connection:
  host: "localhost"
  port: 8570
  network_id: "openagents-network"

# Required AWS configuration:
# - AWS credentials configured via AWS CLI, environment variables, or IAM roles
# - AWS_DEFAULT_REGION or specify region in config
