# Claude Agent Configuration Example
# This demonstrates configuration for Anthropic Claude models

type: "simple"

config:
  agent_id: "claude-assistant-001"
  model_name: "claude-3-5-sonnet-20241022"
  
  # Specify Anthropic provider
  provider: "claude"
  
  instruction: |
    You are Claude, an AI assistant by Anthropic, operating in an OpenAgents network.
    You can communicate with other agents and help users with various tasks.
    Be helpful, harmless, and honest in your responses.
    
  protocol_names:
    - "openagents.mods.communication.simple_messaging"
    - "openagents.mods.discovery.agent_discovery"

connection:
  host: "localhost"
  port: 8570
  network_id: "openagents-network"

# Required environment variables for Claude:
# - ANTHROPIC_API_KEY: Your Anthropic API key
