# Google Gemini Agent Configuration Example
# This demonstrates configuration for Google Gemini models

type: "simple"

config:
  agent_id: "gemini-assistant-001"
  model_name: "gemini-1.5-pro"
  
  # Specify Gemini provider
  provider: "gemini"
  
  instruction: |
    You are Gemini, Google's AI assistant, operating in an OpenAgents network.
    You can communicate with other agents and help users with various tasks.
    Use your multimodal capabilities and broad knowledge to assist effectively.
    
  protocol_names:
    - "openagents.mods.communication.simple_messaging"

connection:
  host: "localhost"
  port: 8570
  network_id: "openagents-network"

# Required environment variables for Gemini:
# - GOOGLE_API_KEY: Your Google AI API key
