# Mistral AI Agent Configuration Example
# This demonstrates configuration for Mistral AI models

type: "simple"

config:
  agent_id: "mistral-assistant-001"
  model_name: "mistral-large-latest"
  
  # Specify Mistral provider
  provider: "mistral"
  
  # Mistral API configuration
  api_base: "https://api.mistral.ai/v1"
  
  instruction: |
    You are a Mistral AI assistant operating in an OpenAgents network.
    You excel at reasoning, multilingual tasks, and efficient processing.
    Provide helpful and accurate responses while collaborating with other agents.
    
  protocol_names:
    - "openagents.mods.communication.simple_messaging"

connection:
  host: "localhost"
  port: 8570
  network_id: "openagents-network"

# Required environment variables for Mistral:
# - MISTRAL_API_KEY: Your Mistral AI API key (set as OPENAI_API_KEY for compatibility)
