# OpenAgents Network Configuration Example

# Network configuration
network:
  name: "ExampleNetwork"
  protocols:
    - type: "openagents.protocols.communication.simple_messaging.protocol.SimpleMessagingNetworkProtocol"
      name: "SimpleMessaging"
      enabled: true
      config: {}

# Service agents configuration
service_agents:
  - name: "Agent1"
    protocols:
      - type: "openagents.protocols.communication.simple_messaging.adapter.SimpleMessagingAgentAdapter"
        name: "SimpleMessaging"
        enabled: true
        config: {}
    services:
      - name: "echo"
        description: "Echo service that returns the input"
    subscriptions:
      - "general"

  - name: "Agent2"
    protocols:
      - type: "openagents.protocols.communication.simple_messaging.adapter.SimpleMessagingAgentAdapter"
        name: "SimpleMessaging"
        enabled: true
        config: {}
    services: []
    subscriptions:
      - "general" 