# OpenAgents Network Configuration Example

# Network configuration
network:
  name: "ExampleNetwork"
  protocols:
    - name: "openagents.protocols.communication.simple_messaging"
      enabled: true
      config: {}

# Service agents configuration
service_agents:
  - name: "Agent1"
    adapters:
      - name: "openagents.protocols.communication.simple_messaging"
        enabled: true
        config: {}
    services:
      - name: "echo"
        description: "Echo service that returns the input"
    subscriptions:
      - "general"

  - name: "Agent2"
    adapters:
      - name: "openagents.protocols.communication.simple_messaging"
        enabled: true
        config: {}
    services: []
    subscriptions:
      - "general"   