# -*- coding: utf-8 -*-
"""
Node endpoints — a device running the launcher daemon, connected to a workspace.

Onboarding flow ("connect a node"):
  1. Owner/admin generates a pairing code in the workspace
     (POST /v1/workspaces/{id}/pairing-codes — see routers/workspaces.py).
  2. The launcher redeems it here (POST /v1/nodes/redeem) → registers a Node and
     receives the workspace token, without the user copy-pasting id + token.
  3. The daemon heartbeats the node (POST /v1/nodes/heartbeat), independent of
     any agent, so the workspace shows the device as connected.
  4. The workspace lists nodes (GET /v1/nodes) with live status.
"""

import logging
import secrets
from datetime import datetime, timedelta, timezone
from typing import Optional

from fastapi import APIRouter, Depends, Header, Query
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.access import resolve_current_user, verify_workspace_access
from app.config import config
from app.database import get_db
from app.models import Node, NodeCommand, NodePairingCode, Workspace
from app.response import ResponseCode, json_response, success_response
from app.routers.network import _workspace_filter

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/v1/nodes", tags=["Nodes"])

NODE_TIMEOUT = timedelta(seconds=config.AGENT_TIMEOUT_SECONDS)

# Pairing codes: 8 chars, no ambiguous glyphs (0/O/1/I/L), shown as XXXX-XXXX.
_CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
_CODE_LEN = 8
PAIRING_TTL = timedelta(minutes=15)


def _now() -> datetime:
    return datetime.now(timezone.utc)


def generate_pairing_code() -> str:
    """A fresh normalized (no-dash) pairing code."""
    return "".join(secrets.choice(_CODE_ALPHABET) for _ in range(_CODE_LEN))


def format_pairing_code(code: str) -> str:
    """Human-facing form: XXXX-XXXX."""
    c = normalize_pairing_code(code)
    return f"{c[:4]}-{c[4:]}" if len(c) == _CODE_LEN else c


def normalize_pairing_code(code: str) -> str:
    """Uppercase and strip separators so 'xxxx-xxxx' == 'XXXXXXXX'."""
    return "".join(ch for ch in (code or "").upper() if ch.isalnum())


def _aware(dt: Optional[datetime]) -> Optional[datetime]:
    """SQLite returns naive datetimes; treat them as UTC for comparison."""
    if dt is not None and dt.tzinfo is None:
        return dt.replace(tzinfo=timezone.utc)
    return dt


def _format_node(node: Node, now: datetime) -> dict:
    status = node.status
    hb = _aware(node.last_heartbeat)
    if hb is None or (now - hb) > NODE_TIMEOUT:
        status = "offline"
    return {
        "nodeId": str(node.id),
        "name": node.name or node.hostname,
        "hostname": node.hostname,
        "deviceType": node.device_type or "unknown",
        "os": node.os,
        "launcherVersion": node.launcher_version,
        "status": status,
        "agents": node.agents or [],
        "runtimes": node.runtimes or [],
        "lastHeartbeatAt": node.last_heartbeat.isoformat() if node.last_heartbeat else None,
        "createdAt": node.created_at.isoformat() if node.created_at else None,
    }


# Remote agent-management actions the daemon knows how to execute.
ALLOWED_COMMAND_ACTIONS = {"create_agent", "start_agent", "stop_agent", "remove_agent", "detect_runtimes"}
# Actions that operate on a single named agent (so the enqueue endpoint requires
# a name). `detect_runtimes` is node-wide and takes no agent.
AGENT_SCOPED_ACTIONS = {"create_agent", "start_agent", "stop_agent", "remove_agent"}


def _format_command(cmd: NodeCommand, *, include_args: bool = False) -> dict:
    out = {
        "commandId": str(cmd.id),
        "action": cmd.action,
        "status": cmd.status,
        "result": cmd.result,
        "agentName": (cmd.command or {}).get("name") if cmd.command else None,
        "createdAt": cmd.created_at.isoformat() if cmd.created_at else None,
        "finishedAt": cmd.finished_at.isoformat() if cmd.finished_at else None,
    }
    if include_args:
        # Only the daemon (machine-authenticated) receives raw args, which may
        # carry an API key for the agent being created.
        out["args"] = cmd.command or {}
    return out


# ---------------------------------------------------------------------------
# Request models
# ---------------------------------------------------------------------------

class NodeRedeemRequest(BaseModel):
    code: str
    node_key: str                       # stable device id generated by the launcher
    name: Optional[str] = None
    hostname: Optional[str] = None
    device_type: Optional[str] = None   # server | laptop | desktop | unknown
    os: Optional[str] = None
    launcher_version: Optional[str] = None


class NodeHeartbeatRequest(BaseModel):
    node_id: str
    hostname: Optional[str] = None
    device_type: Optional[str] = None
    os: Optional[str] = None
    launcher_version: Optional[str] = None
    agents: Optional[list] = None       # current roster [{name, type, status}]
    runtimes: Optional[list] = None     # per-type detection [{type, installed, ready, ...}]


class EnqueueCommandRequest(BaseModel):
    action: str                         # see ALLOWED_COMMAND_ACTIONS
    args: dict = {}                     # create_agent: {name, type, apiKey?, model?, baseUrl?}


class CommandResultRequest(BaseModel):
    ok: bool
    message: Optional[str] = None
    data: Optional[dict] = None


# ---------------------------------------------------------------------------
# POST /v1/nodes/redeem — pair this device to a workspace
# ---------------------------------------------------------------------------

@router.post("/redeem")
def redeem_pairing_code(body: NodeRedeemRequest, db: Session = Depends(get_db)):
    """Redeem a pairing code (the code itself is the credential — no auth header).

    Registers/updates the Node and returns the workspace token so the launcher
    can heartbeat and run agents. Codes are single-use and short-lived.
    """
    code = normalize_pairing_code(body.code)
    if not body.node_key:
        return json_response(ResponseCode.BAD_REQUEST, "Missing node_key")

    pc = db.get(NodePairingCode, code)
    if not pc:
        return json_response(ResponseCode.NOT_FOUND, "Invalid pairing code")
    if pc.redeemed_at is not None:
        return json_response(ResponseCode.CONFLICT, "Pairing code already used")
    now = _now()
    if _aware(pc.expires_at) < now:
        return json_response(ResponseCode.GONE, "Pairing code expired")

    workspace = db.execute(
        select(Workspace).where(Workspace.id == pc.workspace_id)
    ).scalar_one_or_none()
    if not workspace or workspace.status == "deleted":
        return json_response(ResponseCode.NOT_FOUND, "Workspace not found")

    node = db.execute(
        select(Node).where(Node.workspace_id == workspace.id, Node.node_key == body.node_key)
    ).scalar_one_or_none()
    if node is None:
        node = Node(workspace_id=workspace.id, node_key=body.node_key)
        db.add(node)
    node.name = body.name or body.hostname or node.name
    node.hostname = body.hostname or node.hostname
    node.device_type = body.device_type or node.device_type or "unknown"
    node.os = body.os or node.os
    node.launcher_version = body.launcher_version or node.launcher_version
    node.status = "online"
    node.last_heartbeat = now
    db.flush()

    pc.redeemed_at = now
    pc.node_id = node.id
    db.commit()

    return success_response({
        "nodeId": str(node.id),
        "workspaceId": str(workspace.id),
        "workspaceSlug": workspace.slug,
        "workspaceName": workspace.name,
        # The shared workspace token — the node's machine credential from here on.
        "token": workspace.password_hash,
    })


# ---------------------------------------------------------------------------
# POST /v1/nodes/heartbeat — node liveness (authenticated by the workspace token)
# ---------------------------------------------------------------------------

@router.post("/heartbeat")
def node_heartbeat(
    body: NodeHeartbeatRequest,
    db: Session = Depends(get_db),
    x_workspace_token: Optional[str] = Header(None),
):
    node = db.execute(select(Node).where(Node.id == body.node_id)).scalar_one_or_none()
    if not node:
        return json_response(ResponseCode.NOT_FOUND, "Node not found")

    workspace = db.execute(
        select(Workspace).where(Workspace.id == node.workspace_id)
    ).scalar_one_or_none()
    if not workspace:
        return json_response(ResponseCode.NOT_FOUND, "Workspace not found")

    # Machine credential: the workspace token must match.
    if not (x_workspace_token and workspace.password_hash and x_workspace_token == workspace.password_hash):
        return json_response(ResponseCode.UNAUTHORIZED, "Invalid workspace token")

    now = _now()
    node.last_heartbeat = now
    node.status = "online"
    if body.hostname:
        node.hostname = body.hostname
    if body.device_type:
        node.device_type = body.device_type
    if body.os:
        node.os = body.os
    if body.launcher_version:
        node.launcher_version = body.launcher_version
    if body.agents is not None:
        node.agents = body.agents
    if body.runtimes is not None:
        node.runtimes = body.runtimes

    # Deliver any queued remote commands on this heartbeat (the node isn't
    # directly reachable, so the heartbeat is our push channel). Mark them
    # delivered so they aren't handed out twice.
    pending = db.execute(
        select(NodeCommand)
        .where(NodeCommand.node_id == node.id, NodeCommand.status == "pending")
        .order_by(NodeCommand.created_at.asc())
    ).scalars().all()
    for cmd in pending:
        cmd.status = "running"
        cmd.delivered_at = now
    db.commit()

    return success_response({
        "nodeId": str(node.id),
        "status": "online",
        "commands": [_format_command(c, include_args=True) for c in pending],
    })


# ---------------------------------------------------------------------------
# GET /v1/nodes?network=... — list a workspace's nodes (for the UI)
# ---------------------------------------------------------------------------

@router.get("")
def list_nodes(
    network: str = Query(..., description="Workspace ID or slug"),
    db: Session = Depends(get_db),
    x_workspace_token: Optional[str] = Header(None),
    authorization: Optional[str] = Header(None),
):
    workspace = db.execute(
        select(Workspace).where(_workspace_filter(network))
    ).scalar_one_or_none()
    if not workspace or workspace.status == "deleted":
        return json_response(ResponseCode.NOT_FOUND, "Workspace not found")
    if not verify_workspace_access(workspace, x_workspace_token, authorization, db=db):
        return json_response(ResponseCode.UNAUTHORIZED, "Invalid workspace credentials")

    nodes = db.execute(
        select(Node).where(Node.workspace_id == workspace.id).order_by(Node.created_at.asc())
    ).scalars().all()
    now = _now()
    return success_response([_format_node(n, now) for n in nodes])


# ---------------------------------------------------------------------------
# Remote agent management — commands queued for a node's daemon
# ---------------------------------------------------------------------------

@router.post("/{node_id}/commands")
def enqueue_command(
    node_id: str,
    body: EnqueueCommandRequest,
    db: Session = Depends(get_db),
    x_workspace_token: Optional[str] = Header(None),
    authorization: Optional[str] = Header(None),
):
    """Queue a remote agent-management command for a node (owner/admin only).

    The node's daemon receives it on its next heartbeat and runs it locally.
    """
    action = (body.action or "").strip()
    if action not in ALLOWED_COMMAND_ACTIONS:
        return json_response(ResponseCode.BAD_REQUEST, f"Unknown action '{action}'")

    node = db.execute(select(Node).where(Node.id == node_id)).scalar_one_or_none()
    if not node:
        return json_response(ResponseCode.NOT_FOUND, "Node not found")
    workspace = db.execute(
        select(Workspace).where(Workspace.id == node.workspace_id)
    ).scalar_one_or_none()
    if not workspace or workspace.status == "deleted":
        return json_response(ResponseCode.NOT_FOUND, "Workspace not found")
    if not verify_workspace_access(workspace, x_workspace_token, authorization, db=db, min_role="admin"):
        return json_response(ResponseCode.FORBIDDEN, "Only an owner or admin can manage a node's agents")

    args = dict(body.args or {})
    if action in AGENT_SCOPED_ACTIONS:
        if not (args.get("name") or "").strip():
            return json_response(ResponseCode.BAD_REQUEST, "Missing agent name")
        if action == "create_agent" and not (args.get("type") or "").strip():
            return json_response(ResponseCode.BAD_REQUEST, "Missing agent type")

    creator = resolve_current_user(db, authorization)
    cmd = NodeCommand(
        node_id=node.id,
        workspace_id=workspace.id,
        action=action,
        command=args,
        created_by=creator.email if creator else None,
    )
    db.add(cmd)
    db.commit()
    return success_response(_format_command(cmd))


@router.get("/{node_id}/commands")
def list_commands(
    node_id: str,
    db: Session = Depends(get_db),
    limit: int = Query(20, ge=1, le=100),
    x_workspace_token: Optional[str] = Header(None),
    authorization: Optional[str] = Header(None),
):
    """Recent commands for a node, so the UI can show pending/done status."""
    node = db.execute(select(Node).where(Node.id == node_id)).scalar_one_or_none()
    if not node:
        return json_response(ResponseCode.NOT_FOUND, "Node not found")
    workspace = db.execute(
        select(Workspace).where(Workspace.id == node.workspace_id)
    ).scalar_one_or_none()
    if not workspace or workspace.status == "deleted":
        return json_response(ResponseCode.NOT_FOUND, "Workspace not found")
    if not verify_workspace_access(workspace, x_workspace_token, authorization, db=db):
        return json_response(ResponseCode.UNAUTHORIZED, "Invalid workspace credentials")

    cmds = db.execute(
        select(NodeCommand)
        .where(NodeCommand.node_id == node.id)
        .order_by(NodeCommand.created_at.desc())
        .limit(limit)
    ).scalars().all()
    return success_response([_format_command(c) for c in cmds])


@router.post("/commands/{command_id}/result")
def post_command_result(
    command_id: str,
    body: CommandResultRequest,
    db: Session = Depends(get_db),
    x_workspace_token: Optional[str] = Header(None),
):
    """The daemon reports a command's outcome (authenticated by workspace token)."""
    cmd = db.execute(select(NodeCommand).where(NodeCommand.id == command_id)).scalar_one_or_none()
    if not cmd:
        return json_response(ResponseCode.NOT_FOUND, "Command not found")
    workspace = db.execute(
        select(Workspace).where(Workspace.id == cmd.workspace_id)
    ).scalar_one_or_none()
    if not workspace:
        return json_response(ResponseCode.NOT_FOUND, "Workspace not found")
    if not (x_workspace_token and workspace.password_hash and x_workspace_token == workspace.password_hash):
        return json_response(ResponseCode.UNAUTHORIZED, "Invalid workspace token")

    cmd.status = "done" if body.ok else "error"
    cmd.result = {"ok": body.ok, "message": body.message, "data": body.data}
    # Scrub the stored args (may hold an API key) now that we're done with them.
    cmd.command = {"name": (cmd.command or {}).get("name")} if cmd.command else {}
    cmd.finished_at = _now()
    db.commit()
    return success_response(_format_command(cmd))
