# -*- coding: utf-8 -*-
"""
Node endpoints — a device running the launcher daemon, connected to a workspace.

Onboarding flow ("connect a node"):
  1. Owner/admin generates a pairing code in the workspace
     (POST /v1/workspaces/{id}/pairing-codes — see routers/workspaces.py).
  2. The launcher redeems it here (POST /v1/nodes/redeem) → registers a Node and
     receives the workspace token, without the user copy-pasting id + token.
  3. The daemon heartbeats the node (POST /v1/nodes/heartbeat), independent of
     any agent, so the workspace shows the device as connected.
  4. The workspace lists nodes (GET /v1/nodes) with live status.
"""

import logging
import secrets
from datetime import datetime, timedelta, timezone
from typing import Optional

from fastapi import APIRouter, Depends, Header, Query
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.access import resolve_current_user, verify_workspace_access
from app.config import config
from app.database import get_db
from app.models import Node, NodePairingCode, Workspace
from app.response import ResponseCode, json_response, success_response
from app.routers.network import _workspace_filter

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/v1/nodes", tags=["Nodes"])

NODE_TIMEOUT = timedelta(seconds=config.AGENT_TIMEOUT_SECONDS)

# Pairing codes: 8 chars, no ambiguous glyphs (0/O/1/I/L), shown as XXXX-XXXX.
_CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
_CODE_LEN = 8
PAIRING_TTL = timedelta(minutes=15)


def _now() -> datetime:
    return datetime.now(timezone.utc)


def generate_pairing_code() -> str:
    """A fresh normalized (no-dash) pairing code."""
    return "".join(secrets.choice(_CODE_ALPHABET) for _ in range(_CODE_LEN))


def format_pairing_code(code: str) -> str:
    """Human-facing form: XXXX-XXXX."""
    c = normalize_pairing_code(code)
    return f"{c[:4]}-{c[4:]}" if len(c) == _CODE_LEN else c


def normalize_pairing_code(code: str) -> str:
    """Uppercase and strip separators so 'xxxx-xxxx' == 'XXXXXXXX'."""
    return "".join(ch for ch in (code or "").upper() if ch.isalnum())


def _aware(dt: Optional[datetime]) -> Optional[datetime]:
    """SQLite returns naive datetimes; treat them as UTC for comparison."""
    if dt is not None and dt.tzinfo is None:
        return dt.replace(tzinfo=timezone.utc)
    return dt


def _format_node(node: Node, now: datetime) -> dict:
    status = node.status
    hb = _aware(node.last_heartbeat)
    if hb is None or (now - hb) > NODE_TIMEOUT:
        status = "offline"
    return {
        "nodeId": str(node.id),
        "name": node.name or node.hostname,
        "hostname": node.hostname,
        "deviceType": node.device_type or "unknown",
        "os": node.os,
        "launcherVersion": node.launcher_version,
        "status": status,
        "lastHeartbeatAt": node.last_heartbeat.isoformat() if node.last_heartbeat else None,
        "createdAt": node.created_at.isoformat() if node.created_at else None,
    }


# ---------------------------------------------------------------------------
# Request models
# ---------------------------------------------------------------------------

class NodeRedeemRequest(BaseModel):
    code: str
    node_key: str                       # stable device id generated by the launcher
    name: Optional[str] = None
    hostname: Optional[str] = None
    device_type: Optional[str] = None   # server | laptop | desktop | unknown
    os: Optional[str] = None
    launcher_version: Optional[str] = None


class NodeHeartbeatRequest(BaseModel):
    node_id: str
    hostname: Optional[str] = None
    device_type: Optional[str] = None
    os: Optional[str] = None
    launcher_version: Optional[str] = None


# ---------------------------------------------------------------------------
# POST /v1/nodes/redeem — pair this device to a workspace
# ---------------------------------------------------------------------------

@router.post("/redeem")
def redeem_pairing_code(body: NodeRedeemRequest, db: Session = Depends(get_db)):
    """Redeem a pairing code (the code itself is the credential — no auth header).

    Registers/updates the Node and returns the workspace token so the launcher
    can heartbeat and run agents. Codes are single-use and short-lived.
    """
    code = normalize_pairing_code(body.code)
    if not body.node_key:
        return json_response(ResponseCode.BAD_REQUEST, "Missing node_key")

    pc = db.get(NodePairingCode, code)
    if not pc:
        return json_response(ResponseCode.NOT_FOUND, "Invalid pairing code")
    if pc.redeemed_at is not None:
        return json_response(ResponseCode.CONFLICT, "Pairing code already used")
    now = _now()
    if _aware(pc.expires_at) < now:
        return json_response(ResponseCode.GONE, "Pairing code expired")

    workspace = db.execute(
        select(Workspace).where(Workspace.id == pc.workspace_id)
    ).scalar_one_or_none()
    if not workspace or workspace.status == "deleted":
        return json_response(ResponseCode.NOT_FOUND, "Workspace not found")

    node = db.execute(
        select(Node).where(Node.workspace_id == workspace.id, Node.node_key == body.node_key)
    ).scalar_one_or_none()
    if node is None:
        node = Node(workspace_id=workspace.id, node_key=body.node_key)
        db.add(node)
    node.name = body.name or body.hostname or node.name
    node.hostname = body.hostname or node.hostname
    node.device_type = body.device_type or node.device_type or "unknown"
    node.os = body.os or node.os
    node.launcher_version = body.launcher_version or node.launcher_version
    node.status = "online"
    node.last_heartbeat = now
    db.flush()

    pc.redeemed_at = now
    pc.node_id = node.id
    db.commit()

    return success_response({
        "nodeId": str(node.id),
        "workspaceId": str(workspace.id),
        "workspaceSlug": workspace.slug,
        "workspaceName": workspace.name,
        # The shared workspace token — the node's machine credential from here on.
        "token": workspace.password_hash,
    })


# ---------------------------------------------------------------------------
# POST /v1/nodes/heartbeat — node liveness (authenticated by the workspace token)
# ---------------------------------------------------------------------------

@router.post("/heartbeat")
def node_heartbeat(
    body: NodeHeartbeatRequest,
    db: Session = Depends(get_db),
    x_workspace_token: Optional[str] = Header(None),
):
    node = db.execute(select(Node).where(Node.id == body.node_id)).scalar_one_or_none()
    if not node:
        return json_response(ResponseCode.NOT_FOUND, "Node not found")

    workspace = db.execute(
        select(Workspace).where(Workspace.id == node.workspace_id)
    ).scalar_one_or_none()
    if not workspace:
        return json_response(ResponseCode.NOT_FOUND, "Workspace not found")

    # Machine credential: the workspace token must match.
    if not (x_workspace_token and workspace.password_hash and x_workspace_token == workspace.password_hash):
        return json_response(ResponseCode.UNAUTHORIZED, "Invalid workspace token")

    node.last_heartbeat = _now()
    node.status = "online"
    if body.hostname:
        node.hostname = body.hostname
    if body.device_type:
        node.device_type = body.device_type
    if body.os:
        node.os = body.os
    if body.launcher_version:
        node.launcher_version = body.launcher_version
    db.commit()
    return success_response({"nodeId": str(node.id), "status": "online"})


# ---------------------------------------------------------------------------
# GET /v1/nodes?network=... — list a workspace's nodes (for the UI)
# ---------------------------------------------------------------------------

@router.get("")
def list_nodes(
    network: str = Query(..., description="Workspace ID or slug"),
    db: Session = Depends(get_db),
    x_workspace_token: Optional[str] = Header(None),
    authorization: Optional[str] = Header(None),
):
    workspace = db.execute(
        select(Workspace).where(_workspace_filter(network))
    ).scalar_one_or_none()
    if not workspace or workspace.status == "deleted":
        return json_response(ResponseCode.NOT_FOUND, "Workspace not found")
    if not verify_workspace_access(workspace, x_workspace_token, authorization, db=db):
        return json_response(ResponseCode.UNAUTHORIZED, "Invalid workspace credentials")

    nodes = db.execute(
        select(Node).where(Node.workspace_id == workspace.id).order_by(Node.created_at.asc())
    ).scalars().all()
    now = _now()
    return success_response([_format_node(n, now) for n in nodes])
